server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrms-backend
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  main:
    banner-mode: off

logging:
  level:
    org:
      springframework:
        security: DEBUG
# Additional configurations can be added as needed for your specific project.
